"""empty message

Revision ID: 55ee1daab743
Revises: ac0c41d89668
Create Date: 2017-10-28 18:05:17.554566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ee1daab743'
down_revision = 'ac0c41d89668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upcomingworkshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colname', sa.String(length=60), nullable=True),
    sa.Column('seminardate', sa.String(length=60), nullable=True),
    sa.Column('hodname', sa.String(length=60), nullable=True),
    sa.Column('contact', sa.String(length=60), nullable=True),
    sa.Column('expectations', sa.String(length=200), nullable=True),
    sa.Column('mailsenddate', sa.String(length=60), nullable=True),
    sa.Column('followup1', sa.String(length=60), nullable=True),
    sa.Column('followup2', sa.String(length=60), nullable=True),
    sa.Column('confirmation', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('colname'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('followup1'),
    sa.UniqueConstraint('followup2'),
    sa.UniqueConstraint('hodname'),
    sa.UniqueConstraint('mailsenddate'),
    sa.UniqueConstraint('seminardate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upcomingworkshop')
    # ### end Alembic commands ###
